DROP DATABASE IF EXISTS DB_Padrao
CREATE DATABASE DB_Padrao
GO

USE DB_Padrao
GO

DROP TABLE IF EXISTS CESSAO_FUNDO
CREATE TABLE CESSAO_FUNDO (
  ID_CESSAO				INT				NOT NULL IDENTITY(1, 1),
  ORIGINADOR			VARCHAR(250)	NOT NULL,
  DOC_ORIGINADOR		VARCHAR(14)		NOT NULL,
  CEDENTE				VARCHAR(250)	NOT NULL,
  DOC_CEDENTE			VARCHAR(14)		NOT NULL,
  CCB					INT				NOT NULL,
  ID_EXTERNO			INT				NOT NULL,
  CLIENTE				VARCHAR(250)	NOT NULL,
  CPF_CNPJ				VARCHAR(50)		NOT NULL,
  ENDERECO				VARCHAR(250)	NOT NULL,
  CEP					VARCHAR(50)		NOT NULL,
  CIDADE				VARCHAR(250)	NOT NULL,
  UF					VARCHAR(50)		NOT NULL,
  VALOR_DO_EMPRESTIMO	DECIMAL(10,2)	NOT NULL,
  VALOR_PARCELA			DECIMAL(10,2)	NOT NULL,
  TOTAL_PARCELAS		INT				NOT NULL,
  PARCELA				INT				NOT NULL,
  DATA_DE_EMISSAO		DATE			NOT NULL,
  DATA_DE_VENCIMENTO	DATE			NOT NULL,
  PRECO_DE_AQUISICAO	DECIMAL(10,2)	NOT NULL,

  CONSTRAINT [PK_CESSAO_FUNDO] PRIMARY KEY(ID_CESSAO)
)
GO